### PR TITLE
docs: add explicit statement on ignore patterns

### PR DESCRIPTION
**Pull request by rarkins**

### CODE REVIEW

**Review by loeffel-io — APPROVED** [review]

**Comment by loeffel-io** [comment]
thanks @rarkins!

**Comment by loeffel-io** [comment]
@rarkins mentioned you at https://github.com/ls-lint/docs/blob/master/1.x/prologue/contributions.md

**Comment by rarkins** [comment]
@loeffel-io that wasn't necessary, but thanks 👍 

FYI I am in the process of adding it to https://github.com/renovatebot/renovate

**Comment by loeffel-io** [comment]
@rarkins beautiful! sounds great

**Pull request merged**
